### ISSUE TITLE
Error while building FioriAR in Xcode 14.3.1

### ISSUE THREAD

**Issue by sk2023361** [SAP/cloud-sdk-ios-fiori-ar#83]
**Describe the bug**
Error while building a project containing FioriAR in Xcode 14.3.1.

**To Reproduce**
1. Create a new Xcode project using Xcode 14.3.1 (Step 1 of [this tutorial](https://developers.sap.com/tutorials/fiori-ios-btp-fioriar.html))
2. Add FioriAR using Swift Package Manager (Step 2 of [this tutorial](https://developers.sap.com/tutorials/fiori-ios-btp-fioriar.html))
3. Build the project

**Expected behavior**
Project builds with no errors.

**Screenshots**
<img width="1142" alt="Screenshot 2023-07-14 at 20 44 04 copy" src="https://github.com/SAP/cloud-sdk-ios-fiori-ar/assets/139587424/bbc25b60-3ad8-4037-b236-1e47825e3bbb">

**Mobile (please complete the following information):**
 - Device: MacBook Pro 14-inch, 2023
 - OS: macOS 13.4.1 (c)
 - Swift Package Product: FioriAR
 - Swift Package Version: 2.0.0
 - Xcode Version: Xcode 14.3.1 (14E300c)

**Additional context**
Probably the problem is with FioriSwiftUI. The aforementioned issue was fixed in version 3.2.0 of FioriSwiftUI ([link](https://github.com/SAP/cloud-sdk-ios-fiori/commit/3a6879a28bef7c55403fa1a49942157d540f04b4)), but FioriAR uses version 2.2.0 of FioriSwiftUI.

**Comment by MarcoEidinger** [comment]
Thank you @sk2023361 for bringing this to our attention. We'll release a new version shortly in which the build error got fixed.
