### ISSUE TITLE
Error while fetching the SDK via Swift Package Manager

### ISSUE THREAD

**Issue by sk2023361** [SAP/cloud-sdk-ios-fiori-ar#85]
**Describe the bug**
"Package Resolution Failed" error while fetching FioriAR SDK via Swift Package Manager.

**To Reproduce**
1. Create a new Xcode project using Xcode 14.3.1 (Step 1 of [this tutorial](https://developers.sap.com/tutorials/fiori-ios-btp-fioriar.html))
2. Add FioriAR using Swift Package Manager (Step 2 of [this tutorial](https://developers.sap.com/tutorials/fiori-ios-btp-fioriar.html))
3. See "Package Resolution Failed" error

**Expected behavior**
FioriAR SDK is fetched via Swift Package Manager with no errors.

**Screenshots**
How it looks like while trying to fetch the SDK:
<img width="1163" alt="Screenshot 2023-08-08 at 21 45 08" src="https://github.com/SAP/cloud-sdk-ios-fiori-ar/assets/139587424/4c3a2f4c-08d9-416f-91c3-090b98836c6d">

Full description of the errors (can be viewed in Xcode Issue navigator after clicking "Add Anyway" on the previous screenshot):
<img width="874" alt="Screenshot 2023-08-08 at 21 21 57" src="https://github.com/SAP/cloud-sdk-ios-fiori-ar/assets/139587424/24c6caec-f592-4480-b89a-4f3f552674c5">

**Mobile (please complete the following information):**
- Device: MacBook Pro 14-inch, 2023
- OS: macOS 13.5
- Swift Package Product: FioriAR
- Swift Package Version: 3.0.0
- Xcode Version: Xcode 14.3.1 (14E300c)

**Comment by MarcoEidinger** [comment]
You must [configure technical user & password](https://github.com/SAP/cloud-sdk-ios#configuration) for package resolution!

Mentioned in https://github.com/SAP/cloud-sdk-ios-fiori-ar#requirements
