### ISSUE TITLE
App crash on scanning the image anchor

### ISSUE THREAD

**Issue by sk2023361** [SAP/cloud-sdk-ios-fiori-ar#86]
**Describe the bug**
App crash on scanning the image anchor, when following the [Build an Augmented Reality Experience app with FioriAR](https://developers.sap.com/tutorials/fiori-ios-btp-fioriar.html) tutorial.
Log message from Xcode Debug area:
`SwiftUI/Layout.swift:1439: Fatal error: view origin is invalid: (nan, 794.0), UnitPoint(x: 0.0, y: 0.0), (0.0, 0.0)`
Please also find the screenshot and the screen recording video below.

**To Reproduce**
1. Follow Steps 1-10 of [this tutorial](https://developers.sap.com/tutorials/fiori-ios-btp-fioriar.html) using SwiftUI-based version
2. Follow points 1.1, 1.2 and 1.3 of Step 11 of the tutorial
3. Scan the image anchor (point 1.4 of Step 11 of the tutorial)
4. See the app crash

**Expected behavior**
The image anchor is scanned without app crash.

**Screenshots**
<img width="1135" alt="Screenshot 2023-09-14 at 20 41 26" src="https://github.com/SAP/cloud-sdk-ios-fiori-ar/assets/139587424/2a8378c3-8dfb-4d4f-941b-69d3a4dfd73d">

**Video**
https://github.com/SAP/cloud-sdk-ios-fiori-ar/assets/139587424/7ea14ddd-58d7-4d47-9b29-840e79140d8e

**Mobile (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 16.5.1 (c)
 - Swift Package Product: FioriAR
 - Swift Package Version: 3.0.0
 - Xcode Version: 14.3.1 (14E300c)

**Additional context**
We have also tried to download and run the project from the [SAP Samples on GitHub](https://github.com/SAP-samples/mobile-augmented-reality). The result was the same.

**Comment by MarcoEidinger** [comment]
Hi @sk2023361, thanks for reporting the issue. New patch release [3.0.1](https://github.com/SAP/cloud-sdk-ios-fiori-ar/releases/tag/3.0.1) is going to fix the issue. Cheers!
